name = "The Honeybee Podcast"
license = "MIT"
licenselink = "https://github.com/themefisher/bigspring-hugo-startup-theme/blob/master/LICENSE"
description = "The Honeybee Podcast"
tags = ['personal finance', 'singapore', 'financial planning', 'finances', 'money mind', 'cna money', 'the woke salaryman', 'woke salary', 'the simple sum', 'insurance', 'cheapest insurance singapore', 'seedly', 'money sense', 'singapore cpf', 'money talks', 'sgbudgetbabe', 'finance podcast', 'top finance podcast', 'top podcast singapore', ''singapore podcast'', 'top podcast', 'money podcast in singapore', 'singaporeans money', 'financials', 'planning financials', 'money talks', 'buy insurance singapore']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
name = "Honeybee Podcast"
homepage = "https://honeybeepodcast.com/"