baseURL = "https://loving-ardinghelli-656055.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bigspring Hugo"
[markup.goldmark.renderer]
unsafe = true
