############################# Romana ############################
[ro]
languageName = "Ro"
title = "Flamingo Menu"
contentDir = "content/romana" # content/romana
weight = 1
########### footer content ##########
footer_menu_left = "Companie"
# footer_menu_middle = "Produs"
# footer_menu_right = "Suport"
# footer_content = "Ultimul meniu de care vei avea nevoie1aa"
# copyright
copyright = "Construit cu &hearts; în Brașov, România"

############################# English ############################
[en]
languageName = "En"
title = "Flamingo Menu"
contentDir = "content/english" # content/english
weight = 2
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "The last menu you will ever need"
# copyright
copyright = "Made with &hearts; in Brașov, Romania"
