############################# Romana ############################
[ro]
languageName = "Ro"
title = "Flamingo Menu"
contentDir = "content/romana" # content/romana
weight = 1
########### footer content ##########
footer_menu_left = "Companie"
footer_menu_middle = "Produs"
footer_menu_right = "Suport"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Construit cu &hearts; în Brașov, România"

############################# English ############################
[en]
languageName = "En"
title = "Flamingo Menu"
contentDir = "content/english" # content/english
weight = 2
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Made with &hearts; in Brașov, Romania"
